# syntax=docker/dockerfile:1
FROM ubuntu:22.04
# GitHub token
ARG GITHUB_TOKEN=$GITHUB_TOKEN
ENV EGL_PLATFORM=surfaceless

# Set environment variables
ENV CPLUS_INCLUDE_PATH=/usr/local/include
ENV LIBRARY_PATH=/usr/local/lib
ENV CPATH=/usr/local/include
RUN apt-get update && apt-get install -y sudo

# Create a non-root user and add them to the sudo group, allow passwordless sudo
RUN useradd -m -s /bin/bash newuser && \
    echo 'newuser:password' | chpasswd && \
    usermod -aG sudo newuser && \
    echo 'newuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


RUN apt-get update && apt-get install -y sudo

# Install app dependencies and clean up
RUN  apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    xvfb \
    cmake \
    python3-venv \
    libglm-dev \
    libglobjects-dev \
    cmake \
    libgtest-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libglfw3-dev \
    freeglut3-dev \
    libstdc++-12-dev \
    wget \
    libc6-dev \
    libpci3 \
    libelf-dev \
    libglvnd-dev \
    libxau6 \
    libxdmcp6 \
    libxcb1 \
    libxext6 \
    libx11-6 \
    libxv1 \
    libxtst6 \
    libdrm2 \
    libegl1 \
    libgl1 \
    libopengl0 \
    libgles1 \
    libgles2 \
    libglvnd0 \
    libglx0 \
    libglu1 \
    libsm6 \
    libegl-mesa0 \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libgl1-mesa-dri \
    libglx-mesa0 \
    mesa-utils && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*

# Set clang++ as the default C++ compiler
RUN sudo apt-get remove -y gcc
RUN sudo apt-get update -y
RUN sudo apt-get install -y clang
RUN sudo apt-get install -y libgbm-dev libdrm-dev
ENV CXX=clang++


# Install AgarLE
WORKDIR /home/newuser
RUN git clone --recursive https://$GITHUB_TOKEN@github.com/machado-research/AgarLE.git
RUN git clone https://$GITHUB_TOKEN@github.com/machado-research/AgarLE-benchmark.git
WORKDIR /home/newuser/AgarLE-benchmark
RUN python setup.py install --user

# && \
    # sudo pip3 install -r requirements.txt
RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124
RUN pip install git+https://github.com/mayman150/pfrl.git@gymnasium_support

RUN sudo apt-get install -y libglib2.0-0
RUN pip install tqdm
RUN pip install opencv-python
RUN pip install matplotlib
RUN pip install packaging
RUN pip install wandb
